#!/bin/bash
if [ "$DEVPOD" = "true" ]; then
  git config --global push.autoSetupRemote true
  git config --global --add safe.directory /workspaces/devops-study-app
  pre-commit install
  pre-commit install --hook-type commit-msg
fi

if ! command -v cz >/dev/null && [ "$DEVPOD" = "true" ]; then
  pip install --user pipx
  pipx install commitizen
fi
